name: Schedule Update

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  update-schedule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check Secrets
      env:
        SMU_ACCOUNT: ${{ secrets.ACCOUNT }}
        SMU_PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        if [ -z "$SMU_ACCOUNT" ] || [ -z "$SMU_PASSWORD" ]; then
          echo "Error: SMU_ACCOUNT or SMU_PASSWORD secrets are not set."
          exit 1
        fi

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      env:
        UV_INDEX_URL: "https://pypi.org/simple"
      run: uv sync

    - name: Run auto update script
      env:
        SMU_ACCOUNT: ${{ secrets.ACCOUNT }}
        SMU_PASSWORD: ${{ secrets.PASSWORD }}
        SEMESTER_WEEKS: ${{ vars.WEEKS }}
        START_DATE: ${{ vars.START_DATE }}
      run: uv run auto_update.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add schedule.ics
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update schedule.ics" && git push)
